import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Owntime Auth",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-dark-1`}
        suppressHydrationWarning={true}
      >
        <main className="w-full min-h-screen p-5 flex">
          <div className="max-w-[800px] flex items-center justify-center flex-1">
            <Image
              src="./images/Owntime.svg"
              width={280}
              height={140}
              alt="owntime-logo"
            />
          </div>

          {children}
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
