import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import SideNavbar from "@/components/SideNavbar";
import Topbar from "@/components/Topbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Owntime App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-dark-1 flex relative max-w-[1920px] mx-auto`}
        suppressHydrationWarning={true}
      >
        <SideNavbar />

        <main className="p-5">
          <Topbar />

          {children}
        </main>
      </body>
    </html>
  );
}
